dist: trusty
language: r
sudo: required
cache: packages
warnings_are_errors: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-5 g++-5 gfortran-5 ggcov
  - sudo ln -sf /usr/bin/gcov-5 /usr/bin/gcov
  - mkdir ~/.R
  - echo -e "CC=gcc-5 -std=gnu99\nCXX=g++-5 -std=c++11\nCXX1X=g++-5\n" > ~/.R/Makevars
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
