language: r
sudo: true
warnings_are_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-5
  - sudo apt-get -qq install gfortran-5
  - mkdir ~/.R
  - echo -e "CC=gcc-5 -std=gnu99\nCXX=g++-5 -std=c++11\nCXX1X=g++-5\n" > ~/.R/Makevars
  - echo -e "CFLAGS += -O3 -Wall -pipe -pedantic -std=gnu99\n" >> ~/.R/Makevars
  - echo -e "CXXFLAGS += -O3 -Wall -pipe -Wno-unused -pedantic\n" >> ~/.R/Makevars

r_binary_packages:
  - crayon
  - htmltools
  - lazyeval
  - colorspace
  - dichromat
  - formatR
  - gridBase
  - gTable
  - highr
  - irlba
  - iterators
  - labeling
  - markdown
  - plyr
  - proto
  - RColorBrewer
  - registry
  - stringdist
  - testthat
  - xtable
  - yaml
  - foreach
  - knitr
  - pkgmaker
  - reshape2
  - doParallel
  - scales
  - NMF
  - ggplot2
  - igraph

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
