language: r
sudo: true
warnings_are_errors: true

r_binary_packages:
  - crayon
  - htmltools
  - lazyeval
  - colorspace
  - dichromat
  - formatR
  - gridBase
  - gTable
  - highr
  - irlba
  - iterators
  - labeling
  - markdown
  - plyr
  - proto
  - RColorBrewer
  - registry
  - stringdist
  - testthat
  - xtable
  - yaml
  - foreach
  - knitr
  - pkgmaker
  - reshape2
  - doParallel
  - scales
  - NMF
  - ggplot2
  - igraph

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'