language: r
sudo: true
cache: packages
warnings_are_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.8 g++-4.8 gfortran-4.8 ggcov
  - sudo ln -sf /usr/bin/gcov-4.8 /usr/bin/gcov
  - mkdir ~/.R
  - echo -e "CC=gcc-4.8 -std=gnu99\nCXX=g++-4.8 -std=c++11\nCXX1X=g++-4.8\n" > ~/.R/Makevars
  - echo -e "CFLAGS += -g -O2 -Wall -pipe -pedantic -std=gnu99\n" >> ~/.R/Makevars
  - echo -e "CXXFLAGS += -g -O2 -Wall -pipe -Wno-unused -pedantic\n" >> ~/.R/Makevars

install:
  # Install R packages
  - ./travis-tool.sh r_binary_install rcpp rjsonio knitr ggplot2 png
  - ./travis-tool.sh r_install yaml microbenchmark dplyr plyr stringr RcppArmadillo
  - ./travis-tool.sh github_package hadley/pryr hadley/lineprof


r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
